kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: yaltaroute 
  namespace: yalta 
spec:
  host: tls1.chl.mq.ibm.com
  to:
    kind: Service
    name: yalta-queue-manager-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
